Feature/authentication
CollegeSchedule/cs-apple pull request #5
Opened 2020-11-05 13:22 UTC by EverlastingHolder

2020-11-10 09:51 UTC, WhyWeLive requested changes

2020-11-10 09:51 UTC, WhyWeLive commented on Shared/Component/DarkBlueShadowProgressViewStyle.swift
> +                color: Color(red: 0, green: 0, blue: 0.6),
Нужно вынести в папку assets как ProgressDarkBlueShadowColor

2020-11-10 09:51 UTC, WhyWeLive commented on Shared/Component/InlinePickerView.swift
> +                    alpha: 1
Нужно вынести в папку assets как InlinePickerButtonBackgroundColor

2020-11-10 09:51 UTC, WhyWeLive commented on Shared/Component/Logo.swift
> +        ]
В папку assets

2020-11-10 11:37 UTC, WhyWeLive requested changes

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Component/InlinePickerView.swift
>                  : UIColor.white
Format lines

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Component/Logo.swift
> +}
Format lines

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Anonymous/Authentication/AuthenticationViewModel.swift
> +        > {
Format lines

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Marks/MarksSubject/MarksSubjectItemView.swift
> +
```suggestion
            }
            
            Spacer()
            
```

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Marks/MarksSubject/MarksSubjectView.swift
> +        let subject: String
```suggestion
    }
    
    struct SubjectItem: Hashable {
        let subject: String
```

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Marks/MarksView.swift
> +                MarksSubjectView()
```suggestion
            if self.selection == 0 {
                Text("ff")
            } else{
                MarksSubjectView()
```

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Navigation/NavigationItem.swift
>          case .search: return "Поиск"
localize

2020-11-10 11:37 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Search/ListViewItem.swift
> +                    NavigationLink("См. Все", destination: Text("All"))
Localize

2020-11-11 06:45 UTC, WhyWeLive approved these changes
LGTM

2020-12-12 03:56 UTC, WhyWeLive requested changes

2020-12-12 03:56 UTC, WhyWeLive commented on Shared/Component/SearchBar.swift
> +
```suggestion
```

2020-12-12 03:56 UTC, WhyWeLive commented on Shared/Data/Entity/CollectionMetaResponse.swift
> +struct CollectionMetaResponse<T: Codable&Hashable>: Codable, Hashable {
```suggestion
struct CollectionMetaResponse<T: Codable & Hashable>: Codable, Hashable {
```

2020-12-12 03:56 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Search/ListViewItem.swift
> +struct ListViewItem<T: Hashable&Codable>: Hashable {
```suggestion
struct ListViewItem<T: Hashable & Codable>: Hashable {
```

2020-12-12 03:56 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Search/ScheduleListSeeAllView.swift
> +struct ScheduleListSeeAllView<T: Codable&Hashable, Content: View>: View {
```suggestion
struct ScheduleListSeeAllView<T: Codable & Hashable, Content: View>: View {
```

2020-12-12 03:56 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Search/ScheduleListSeeAllView.swift
> +        }.navigationTitle("Аккаунты")
Локализация

2020-12-24 13:53 UTC, WhyWeLive requested changes

2020-12-24 13:53 UTC, WhyWeLive commented on Shared/Component/APIResultView.swift
> +            EmptyView()
```suggestion
            ProgressView()
```

2020-12-24 13:53 UTC, WhyWeLive commented on Shared/Extension/Date.swift
> +    }()
```suggestion
    static let DAY_IN_WEEK: Date = Date().addingTimeInterval(86400 * 7)
    
    static let TOMORROW: Date = Date().addingTimeInterval(86400)
    
    static let YESTERDAY: Date = Date().addingTimeInterval(-86400)
```

2020-12-24 13:53 UTC, WhyWeLive commented on Shared/Feature/Authenticated/Schedule/Component/ScheduleView/ScheduleItemView.swift
> +    }
Не думаю, что создавать объект форматтера является наилучшей идеей.

2020-12-24 15:51 UTC, EverlastingHolder commented on Shared/Feature/Authenticated/Schedule/Component/ScheduleView/ScheduleItemView.swift
> +    }
ты про это ? let formatter = DateComponentsFormatter()

2020-12-29 07:38 UTC, WhyWeLive approved these changes

2020-12-29 07:38 UTC, merged